default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5

development:
  <<: *default
  database: termometro_development
  username: termometro
  password: footermometrobar

test:
  <<: *default
  database: termometro_test

production:
  <<: *default
  database: termometro_production
  username: termometro
  password:
